START TRANSACTION;
ALTER TABLE "Users" ADD "AccessFailedCount" integer NOT NULL DEFAULT 0;

ALTER TABLE "Users" ADD "ConcurrencyStamp" character varying(255);

ALTER TABLE "Users" ADD "LockoutEnabled" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Users" ADD "LockoutEnd" timestamp with time zone;

ALTER TABLE "Users" ADD "NormalizedEmail" character varying(255);

ALTER TABLE "Users" ADD "NormalizedUserName" character varying(255);

ALTER TABLE "Users" ADD "SecurityStamp" character varying(255);

ALTER TABLE "Users" ADD "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Users" ADD "UserName" character varying(255) NOT NULL DEFAULT '';

UPDATE "Users"
SET "UserName" = COALESCE(NULLIF("UserName", ''), "Email"),
    "NormalizedUserName" = COALESCE("NormalizedUserName", UPPER("Email")),
    "NormalizedEmail" = COALESCE("NormalizedEmail", UPPER("Email")),
    "SecurityStamp" = COALESCE("SecurityStamp", "Id"::text),
    "ConcurrencyStamp" = COALESCE("ConcurrencyStamp", "Id"::text),
    "LockoutEnabled" = TRUE
WHERE "Email" IS NOT NULL;

CREATE TABLE "AspNetRoles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('11111111-1111-1111-1111-111111111111', '11111111-1111-1111-1111-111111111111', 'Parent', 'PARENT');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('22222222-2222-2222-2222-222222222222', '22222222-2222-2222-2222-222222222222', 'Player', 'PLAYER');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('33333333-3333-3333-3333-333333333333', '33333333-3333-3333-3333-333333333333', 'Coach', 'COACH');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('44444444-4444-4444-4444-444444444444', '44444444-4444-4444-4444-444444444444', 'TeamManager', 'TEAMMANAGER');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('55555555-5555-5555-5555-555555555555', '55555555-5555-5555-5555-555555555555', 'AcademyDirector', 'ACADEMYDIRECTOR');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('66666666-6666-6666-6666-666666666666', '66666666-6666-6666-6666-666666666666', 'OrganizationAdmin', 'ORGANIZATIONADMIN');
INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('77777777-7777-7777-7777-777777777777', '77777777-7777-7777-7777-777777777777', 'PlatformAdmin', 'PLATFORMADMIN');

CREATE INDEX "EmailIndex" ON "Users" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "Users" ("NormalizedUserName");

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260501153246_AddIdentityAccountSupport', '9.0.15');

COMMIT;

